// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/ping/resolver.go

// Package ping is a generated GoMock package.
package ping

import (
	net "net"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAddressResolver is a mock of AddressResolver interface.
type MockAddressResolver struct {
	ctrl     *gomock.Controller
	recorder *MockAddressResolverMockRecorder
}

// MockAddressResolverMockRecorder is the mock recorder for MockAddressResolver.
type MockAddressResolverMockRecorder struct {
	mock *MockAddressResolver
}

// NewMockAddressResolver creates a new mock instance.
func NewMockAddressResolver(ctrl *gomock.Controller) *MockAddressResolver {
	mock := &MockAddressResolver{ctrl: ctrl}
	mock.recorder = &MockAddressResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressResolver) EXPECT() *MockAddressResolverMockRecorder {
	return m.recorder
}

// ResolveDestination mocks base method.
func (m *MockAddressResolver) ResolveDestination(dest string) (net.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveDestination", dest)
	ret0, _ := ret[0].(net.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveDestination indicates an expected call of ResolveDestination.
func (mr *MockAddressResolverMockRecorder) ResolveDestination(dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveDestination", reflect.TypeOf((*MockAddressResolver)(nil).ResolveDestination), dest)
}

// ResolveSource mocks base method.
func (m *MockAddressResolver) ResolveSource() (net.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSource")
	ret0, _ := ret[0].(net.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSource indicates an expected call of ResolveSource.
func (mr *MockAddressResolverMockRecorder) ResolveSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSource", reflect.TypeOf((*MockAddressResolver)(nil).ResolveSource))
}
